### ISSUE TITLE
Move common CUDA API functionality to CUDAapi.jl

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAdrv.jl#11]
EDIT: changed approach, don't make CUDArt build upon CUDAdrv, as the API's are really distinct. Move common functionality to a third package.

There's similar concepts/structures in both CUDArt.jl and CUDAdrv.jl. With CUDArt depending on CUDAdrv nowadays, we could try and deduplicate some of those. At the same time, it does depend on those concepts being compatible between the driver and runtime API...

Candidates (in order of difficulty):
- Devices: seems represented by plain integers in both APIs, so should be compatible.
- Streams: CUDArt streams map onto CUDAdrv streams anyway, and the runtime API calls acting on streams have counterparts in the driver API
- CUDAdrv's `DevicePtr`vs CUDArt's `Ptr`: seems more fleshed out in CUDAdrv, but depends on a context which is implicit in CUDArt
- CUDAdrv's `CuArray` vs CUDArt's: depends on whether these are compatible at the API level. Many more features in CUDArt's version, but better (?) gc integration at the CUDAdrv side

**Comment by SimonDanisch** [comment]
:100:

**Comment by vchuravy** [comment]
A lot of ~CUDAdrv~ CUDArt array features could either be replaced by `CUDAnative` or `GPUArrays`.

**Comment by maleadt** [comment]
?? CUDAdrv arrays are host arrays, which aren't part of CUDAnative. And I don't think GPUArrays will ever support all of CUDA's array types; I imagine it will be a Plots.jl-style wrapper of underlying vendor-specific packages/types, eg. building upon CUDAdrv or CUDArt's array type but adding operators executing kernels using CUDAnative?

**Comment by vchuravy** [comment]
Sorry I should have expressed myself clearer. I meant CUDArt CudaArrays and as an example the current implementation of `fill`. I dislike the current implementation of `CuFunction` with `ptxdict` and think that explicitly managing them might be clearer and easier.

**Comment by SimonDanisch** [comment]
I think it's a bit different from Plots.jl, since it's goal is to combine multiple low-level libraries of one Vendor and offer an exchange layer between different Vendors.
So I do think, packages like `CUDArt` should be as low level as possible. Where we should draw the line is not entirely clear though ;)
In the future, I'd like to have the buffers/images/arrays in the low level packages as a 1:1 port of the underlying API. But that's disputable ;)
This leaves room for low level libraries to concentrate on being a good wrapper and we can have more high level code concentrated in one place.
The advantage of that is, that you can share quite a lot of code on higher levels between different APIs ;)
`fill` is a good example, which should only be in GPUArrays. You can define it easily for all vendors by using map/broadcast ;)

**Comment by maleadt** [comment]
> I think it's a bit different from Plots.jl, since it's goal is to combine multiple low-level libraries of one Vendor and offer an exchange layer between different Vendors.

Oh yeah, inter-vendor compatibility is definitely a huge plus compared to the level of interoperability Plots.jl offers.

> `fill` is a good example, which should only be in GPUArrays. 

But the CUDA API's expose a `memset` which I assume would be a much more efficient implementation of `fill` (ie. not requiring a kernel launch to implement the map/broadcast)

> I meant CUDArt CudaArrays and as an example the current implementation of `fill`

The problem is that there really are two distinct Array types: one by the [driver API](http://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1g4192ff387a81c3bd5ed8c391ed62ca24), and one by the [runtime API](http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g6728eb7dc25f332f50bdb16a19620d3d). As with the contexts, these _might_ be compatible behind the scenes. But should we bother figuring that out, and if so, deduplicating our array support in CUDAdrv/CUDAdrv? In a way, NVIDIA is exposing two distinct API's, so we should be wrapping both distinctly and not be mixing them.

That is, if we want to have both the driver API and runtime API available. Assuming neither of the APIs is going away (we should verify this with NVIDIA), and most of not all features are present in both APIs (albeit wrapped in a distinct manner), maybe we should just focus on advancing one of our packages and making sure users can do everything with it they want to? If not, we would be duplicating a lot of code, with really minimal interoperability guarantees (I think NVIDIA only documents how to make share contexts).

**Comment by SimonDanisch** [comment]
In that case, I think there can still be an argument for letting `memset` be `memset` in a lower level wrapper, and specialize to a more performant implementation in a higher level package.

>maybe we should just focus on advancing one of our packages and making sure users can do everything with it they want to

Sounds lovely :)

**Comment by maleadt** [comment]
#54
