### ISSUE TITLE
How to use CUDAdrv.@profile? 

### ISSUE THREAD

**Issue by johnnychen94** [JuliaGPU/CUDAdrv.jl#111]
I see the @profile macro here https://github.com/JuliaGPU/CUDAdrv.jl/blob/f859392a4f4b4d6384d9a985e5ac258547d873c6/src/profile.jl#L9

But there's no instructions on how can I see the profile results, so I'm wondering how can I use this function. For example... (Is this too simple to sample?)

```julia
using CUDAdrv, CUDAnative
function kernel_vadd(a, b, c)
    i = (blockIdx().x-1) * blockDim().x + threadIdx().x
    c[i] = a[i] + b[i]
    return
end

a = round.(rand(Float32, (3000, 4000)) * 100)
b = round.(rand(Float32, (3000, 4000)) * 100)
d_a = CuArray(a)
d_b = CuArray(b)
d_c = similar(d_a)  # output array

CUDAdrv.@profile @cuda threads=12 kernel_vadd(d_a, d_b, d_c) # returns nothing
```

**Comment by maleadt** [comment]
Please use backticks to surround at-something, eg. `@profile`, or you generate notifications for the user with that name.

The documentation mentions how you need external tools:

```
help?> @profile
  @profile ex

  Run expressions while activating the CUDA profiler.

  Note that this API is used to programmatically control the profiling granularity by allowing profiling to be done only on selective pieces of code. It does not perform any profiling on itself, you need external tools for that.
```

Specifically, you can use `nvprof`, `nvvp`, or even the new Nsight Compute profiler from CUDA 10.

Also, please use the Discourse forums for support questions.

**Comment by johnnychen94** [comment]
Thanks for pointing out, I'll keep this in mind.

**Comment by maleadt** [comment]
It is possible to use CUPTI for profiling/reflection within Julia, see https://github.com/JuliaGPU/CUDAnative.jl/issues/219, but that would require quite some engineering and the NVIDIA tools are really good, so just use those :slightly_smiling_face:
