### ISSUE TITLE
Unable to find libcuda

### ISSUE THREAD

**Issue by jcreinhold** [JuliaGPU/CUDAdrv.jl#119]
I am trying to install CUDAdrv, but it is unable to find the cuda library which causes the build to fail. Specifically, the error raised during installation is:

```julia
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed CUDAdrv ─ v1.0.0
  Updating `~/.julia/environments/v1.0/Project.toml`
  [c5f51814] + CUDAdrv v1.0.0
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [c5f51814] + CUDAdrv v1.0.0
  [de0858da] + Printf
  [4ec0a83e] + Unicode
  Building CUDAdrv → `~/.julia/packages/CUDAdrv/ZyWFc/deps/build.log`
┌ Error: Error building `CUDAdrv`:
│ Could not find CUDA driver library.
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097
```

Looking at the build.jl code where the error is raised, I see that CUDAapi is failing to find the cuda library. If I run this command myself, I get the following results:

```julia
julia> using CUDAapi

julia> find_toolkit()
1-element Array{String,1}:
 "/software/apps/cuda/9.2"

julia> find_cuda_library("cuda")

julia> find_cuda_library("cuda", find_toolkit())

```

where the last two commands return nothing. I'm thinking that this is failing because of the odd location of the cuda library. Note that the `find_toolkit` uses the set `CUDA_HOME` environment variable which defines the location as `/software/apps/cuda/9.2`. For reference, `libcuda.so` is present in `/usr/lib64/`. 

Any idea on how to get the install to find the cuda library?

Thank you for the help.

**Comment by maleadt** [comment]
`libcuda` is your system/OS-specific kernel library, and should just be system-discoverable, and doesn't need to be under `CUDA_HOME`. That's why CUDAapi's` find_cuda_library` just falls back to `Libdl.find_library`. Strange how that doesn't seem to look in `/usr/lib64`, are there other libraries there that you can discover with `Libdl.find_library`? Try starting Julia with `LD_LIBRARY_PATH=/usr/lib64`, if that works you're probably missing an entry in `/etc/ld.so.conf`.

**Comment by jcreinhold** [comment]
After some more testing and a response back from the sys admin, I was able to get the package installed. The problem was due to a quirk in the way a [singularity image](https://www.sylabs.io/singularity/) which contained the julia installation was called. Thank you very much for the feedback. Closing the issue.

**Comment by maleadt** [comment]
Great!
