### ISSUE TITLE
Support multiple CUDA versions in one build

### ISSUE THREAD

**Issue by simonbyrne** [JuliaGPU/CUDAdrv.jl#143]
I'm trying to use a common build directory across a cluster which has different versions of CUDA installed on different machines (they re-image the nodes incrementally), and I keep getting the error
```
InitError: ERROR: CUDA driver library has changed. Please run Pkg.build("CUDAdrv") and restart Julia.
```

Is there any way we could make this work with different versions? From what I understand the CUDA driver is backwards compatible, so it would be useful if I could say manually specify say `JULIA_CUDA_DRIVER_VERSION` which would then work with any CUDA driver newer than this?

**Comment by maleadt** [comment]
Sorry for the delay. I don't think this is easy though, although feasible for CUDAdrv (which only caches the `libcuda` path and version), you'd be running in the same issue for CUDAnative/CuArrays where much more information is discovered or determinde at build time, such as the supported compute model (not always backwards compatible), paths to various utilities and libraries, etc. Some of this info is used to conditionally define methods or switch implementations. Making sure all that is deferred to `__init__` time, invalidating the results when necessary, and being careful about not precompiling any of these values (`Ref` all the things?) seems like quite some complexity.

We could try and do it nicely by having some `Build` object that contains all the info and lazily generating it at run time & writing to disk, but that feels like defeating the purpose of `Pkg.Build`. Although it would also simplify Docker images (where CUDA isn't available at build time).

**Comment by maleadt** [comment]
I think I might have a solution that combines best of both worlds: the ability to conditionally define methods and only reconfigure when needed, without the annoyances of `Pkg.build`:

```julia
module WIP

# here we do the kind of detection that we used to do in deps/ext.jl
const configured = rand(Bool)

if configured
    const path = "yes"
else
    # default values to keep the package loadable
    const path = nothing
end

function __init__()
    if rand(Bool) # detect if set-up changed
        cachefile = Base.compilecache(Base.PkgId(WIP))
        rm(cachefile)
        error("Your set-up changed, WIP.jl needs to be reconfigured. Please load the package again.")
    end
end

end # module
```

This would basically embed the state in the precompile image (which would still not be usable across multiple hosts, is that fine for your use case @simonbyrne?).

cc @vchuravy

**Comment by simonbyrne** [comment]
Well, my immediate issue was solved by the cluster finishing re-imaging their nodes, but I think something like this could work.

The downside is that it can be a bit confusing and harder to debug: RCall.jl used to do something similar to find the local R installation, but it got too complicated so we switched to using deps.

**Comment by maleadt** [comment]
> The downside is that it can be a bit confusing and harder to debug

We could write the determined configuration to a file much like `deps/ext.jl` nowadays. What would be a good, cluster-compatible location for such a log?

**Comment by simonbyrne** [comment]
I'm not sure: the Julia package manager still has a few pain points when it comes to clusters and shared file systems.

Having thought a bit more about it, I think the simplest model is along the lines of what you propose, using multiple depots: in that way, the first depot would be per-node, and could contain the compile cache, and a lateer shared one could contain the package code.

**Comment by simonbyrne** [comment]
@vchuravy : you have a bit more experience with clusters: any thoughts?

**Comment by maleadt** [comment]
Or just add enough `@debug` statements to the global initialization code and ask users to toggle `JULIA_DEBUG=CUDAdrv` when filing bugs, it should provide the same info as posting the contents of `ext.jl`. I'll try and have a crack at this later this week.

**Comment by maleadt** [comment]
There is still one file that is generated at run time though: the CUDAnative runtime library.
We currently put that in the `deps` folder, that's wrong. Proposal, a `CUDAnative/runtime` subdir in:
- Unix: `get(ENV, "XDG_CACHE_HOME", joinpath(homedir(), ".cache"))`
- macOS: `~/Library/Caches/`
- Windows: `%LOCALAPPDATA%`

**Comment by vchuravy** [comment]
Hm other packages do install things to `.julia`. IJulia uses `prefs/IJulia` conda creates a `conda` folder. There is `config`. Maybe the right place is `.julia/cache/CUDAnative/$SLUG`?

**Comment by simonbyrne** [comment]
I something like this would also be required for Singularity containers as well.

**Comment by maleadt** [comment]
@vchuravy I put stuff in `compiled` next to the precompile image, e.g. `.julia/compiled/CUDAnative/SLUG.ji` -> `.julia/compiled/CUDAnative/SLUG/runtime`.
Other aspects of this issue are fixed in open PRs, so closing this.
