### ISSUE TITLE
Add support for asynchronous 3-D memcopy (cudaMemcpy3DAsync)

### ISSUE THREAD

**Issue by samo-lin** [JuliaGPU/CUDAdrv.jl#149]
The objective is e.g. to be able to achieve the equivalent of what the following CUDA C code does:
```
int main(){
  const size_t nx = 512;
  const size_t ny = 512;
  const size_t nz = 512;
  float *d_src, *h_dst;
  cudaMalloc(&d_src, nx*ny*nz*sizeof(float));
  cudaHostAlloc(&h_dst, nx*nz*sizeof(float), cudaHostAllocDefault);
  cudaMemset(d_src, 0, nx*ny*nz*sizeof(float));
  memset(h_dst, 1, nx*nz*sizeof(float));

  cudaMemcpy3DParms cpy_params = {0};
  cpy_params.srcPtr = make_cudaPitchedPtr(d_src, nx*sizeof(float), nx, ny);
  cpy_params.dstPtr = make_cudaPitchedPtr(h_dst, nx*sizeof(float), nx, 1);
  cpy_params.srcPos = make_cudaPos((size_t) 0, (size_t) 1, (size_t) 0);
  cpy_params.dstPos = make_cudaPos((size_t) 0, (size_t) 0, (size_t) 0);
  cpy_params.extent = make_cudaExtent(nx*sizeof(float), 1, nz);
  cpy_params.kind   = cudaMemcpyDeviceToHost;

  for (int i=0; i<100; i++){
    cudaMemcpy3DAsync(&cpy_params);
  }

  cudaDeviceSynchronize();
}
```
It reaches about 12 GB/s (Giga: 1e9) with 16 PCIe 3.0 lanes and a NVIDIA Tesla P100.

A corresponding code using multiple 1-D memcopy calls instead reached only about 1.5 GB/s in some experiments reported in the Julia discourse. The Julia discourse topic discussing this issue is found [here](https://discourse.julialang.org/t/cuarrays-cudanative-cudadrv-equivalent-to-cudamemcpy3dasync/26182/8).

**Comment by maleadt** [comment]
Try this:

```julia
using CUDAdrv

@enum(CUmemorytype, MEMORYTYPE_HOST = Cint(1),
                    MEMORYTYPE_DEVICE = Cint(2),
                    MEMORYTYPE_ARRAY = Cint(3),
                    MEMORYTYPE_UNIFIED = Cint(4))

const CuArray_t = Ptr{Cvoid}

struct CuMemcpy3D_st
    srcXInBytes::Csize_t        # Source X in bytes
    srcY::Csize_t               # Source Y
    srcZ::Csize_t               # Source Z
    srcLOD::Csize_t             # Source LOD
    srcMemoryType::CUmemorytype # Source memory type (host, device, array)
        srcHost::Ptr{Cvoid}         # Source host pointer
        srcDevice::CuPtr{Cvoid}     # Source device pointer
        srcArray::CuArray_t         # Source array reference
        reserved0::Ptr{Cvoid}       # Must be NULL
        srcPitch::Csize_t           # Source pitch (ignored when src is array)
        srcHeight::Csize_t          # Source height (ignored when src is array; may be 0 if Depth==1)

    dstXInBytes::Csize_t        # Destination X in bytes
    dstY::Csize_t               # Destination Y
    dstZ::Csize_t               # Destination Z
    dstLOD::Csize_t             # Destination LOD
    dstMemoryType::CUmemorytype # Destination memory type (host, device, array)
        dstHost::Ptr{Cvoid}         # Destination host pointer
        dstDevice::CuPtr{Cvoid}     # Destination device pointer
        dstArray::CuArray_t         # Destination array reference
        reserved1::Ptr{Cvoid}       # Must be NULL
        dstPitch::Csize_t           # Destination pitch (ignored when dst is array)
        dstHeight::Csize_t          # Destination height (ignored when dst is array; may be 0 if Depth==1)

    WidthInBytes::Csize_t       # Width of 3D memory copy in bytes
    Height::Csize_t             # Height of 3D memory copy
    Depth::Csize_t              # Depth of 3D memory copy
end
@assert sizeof(CuMemcpy3D_st) == 200


using CuArrays

Base.pointer(A::CuArray) = A.buf.ptr

function main(nx = 512, ny=512, nz=512)
    d_src = CuArrays.zeros(Float32, (nx, ny, nz))

    h_buf = Mem.alloc(Mem.HostBuffer, nx*nz*sizeof(Float32))
    h_dst = unsafe_wrap(Array, convert(Ptr{Float32}, h_buf), (nx,nz))
    fill!(h_dst, 1)

    copy_params = Ref(CuMemcpy3D_st(
        0, 1, 0,
        0,
        MEMORYTYPE_DEVICE,
        C_NULL,
        pointer(d_src),
        C_NULL,
        C_NULL,
        nx*sizeof(Float32),
        ny,

        0, 0, 0,
        0,
        MEMORYTYPE_HOST,
        pointer(h_dst),
        CU_NULL,
        C_NULL,
        C_NULL,
        nx*sizeof(Float32),
        1,

        nx * sizeof(Float32),
        1,
        nz
    ))

    CUDAdrv.@apicall(:cuMemcpy3D, (Ptr{CuMemcpy3D_st},), copy_params)

    return
end
main()
```

Only superficially tested, so you might need to fiddle with the params (i.e. bytesize vs logical ones). Please report back about any such fixes.

**Comment by samo-lin** [comment]
Great, thank you very much! I will try that out...

**Comment by samo-lin** [comment]
All the arguments seem perfectly right to me when comparing with the [corresponding entry in the NVIDIA driver doc](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1g79f4f3fde6ae0f529568d881d9e11987) and correspond exactly to the CUDA C code in the issue description. I got then also the same 12 GB/s throughput (tested with Float64). All seems perfect. :)

**Comment by maleadt** [comment]
Great! Marking this an intro issue now that some working code is available.

**Comment by samo-lin** [comment]
I was actually looking for the async version of 3-D memcopy (`cuMemcpy3DAsync` in the CUDA driver API).

Is it right that the `@apicall` becomes then as follows?
```
CUDAdrv.@apicall(:cuMemcpy3DAsync, (Ptr{CuMemcpy3D_st}, CuStream_t), copy_params, custream.handle)
```
where `custream` is of type `CuStream` (created e.g. with `custream = CuStream(CUDAdrv.STREAM_NON_BLOCKING);`) and
`const CuStream_t = Ptr{Cvoid}`.

Note that the stream is an optional argument for `cuMemcpy3DAsync`.

**Comment by maleadt** [comment]
> Is it right that the `@apicall` becomes then as follows?

Don't pass `custream.handle`, just `custream` is sufficient. It'll get automatically converted because of how `ccall` works. Other than that, that looks OK.

> Note that the stream is an optional argument for `cuMemcpy3DAsync`.

Optional arguments don't exist in C, so you need to pass the default stream (`CuDefaultStream`) in that  case.

**Comment by samo-lin** [comment]
> Other than that, that looks OK.

Thanks!

> Optional arguments don't exist in C, so you need to pass the default stream (CuDefaultStream) in that case.

Sure, sorry. I was thinking about the corresponding function of the CUDA runtime API, `cudaMemcpy3DAsync`, which has the following (C++) signature:
```
__host__ ​ __device__ ​cudaError_t cudaMemcpy3DAsync ( const cudaMemcpy3DParms* p, cudaStream_t stream = 0 )
```
but this doesn't really matter as you use the CUDA driver API.
