### ISSUE TITLE
v4.0.1 fails to initialize on windows due to mis-named libcuda

### ISSUE THREAD

**Issue by alandion** [JuliaGPU/CUDAdrv.jl#174]
On windows, the `cuInit` function (and all other driver functions) resides in the driver library named "nvcuda.dll" rather than "libcuda.dll".  CUDAdrv v4.0.1 fails to initialize with 
```
┌ Error: CUDAdrv.jl failed to initialize; the package will not be functional.
│ To silence this message, import with ENV["CUDA_INIT_SILENT"]=true,
│ and be sure to inspect the value of CUDAdrv.functional().
│   exception =
│    error compiling __hidden_init__: error compiling cuInit: could not load library "libcuda"
│    The specified module could not be found.
```
A possible temporary workaround for windows users is to make a link from nvcuda.dll to libcuda.dll .

**Comment by maleadt** [comment]
Ah yes, I didn't think of this when changing the `ccall` invocation in the latest release. Will fix.
