### ISSUE TITLE
Wrap cuLaunchHostFunc

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAdrv.jl#229]
Somehing like:

```
using CUDAnative
using CUDAdrv

async_send(data::Ptr{Cvoid}) = ccall(:uv_async_send, Cint, (Ptr{Cvoid},), data)

function launch_host_func(f, stream::CuStream=CuDefaultStream())
    cond = Base.AsyncCondition() do _
        f()
    end

    callback = @cfunction(async_send, Cint, (Ptr{Cvoid},))
    CUDAdrv.cuLaunchHostFunc(stream, callback, cond)
end

c = Condition()
launch_host_func() do
    println("42")
    notify(c)
end
wait(c)
```

Need to think about the context that will be used in the host func. Maybe it doesn't matter because you can't call CUDA stuff from there anyway.

**Comment by vchuravy** [comment]
> Maybe it doesn't matter because you can't call CUDA stuff from there anyway.

Once actually could since `f` is executed as a normal Julia task and the `stream` is unblocked as soon as `uv_async_send` is called.

x-ref: https://github.com/JuliaGPU/KernelAbstractions.jl/pull/85

I went with:
```
async_send(data::Ptr{Cvoid}) = ccall(:uv_async_send, Cint, (Ptr{Cvoid},), data)
function launch_host_func(f, stream::CuStream=CuDefaultStream())
    cond = Base.AsyncCondition() do async_cond
        f()
        close(async_cond)
    end

    callback = @cfunction(async_send, Cint, (Ptr{Cvoid},))
    CUDAdrv.cuLaunchHostFunc(stream, callback, cond)
end
```

Since that will end the waiting task and allow the `cond` to be free'd IIUC
