### ISSUE TITLE
 CUDA error: invalid device ordinal (code #101, ERROR_INVALID_DEVICE)

### ISSUE THREAD

**Issue by liwen-alt** [JuliaGPU/CUDAdrv.jl#245]
![image](https://user-images.githubusercontent.com/63285313/85010302-5f463680-b192-11ea-8bdf-e7f6cf965e73.png)
![image](https://user-images.githubusercontent.com/63285313/85010365-76852400-b192-11ea-88a0-57019af205c9.png)

**Comment by maleadt** [comment]
How many GPUs do you have? If you only have one, `device!(1)` is going to fail (devices are 0-indexed).

**Comment by liwen-alt** [comment]
I have  only one  is GEFORCE 830M,

**Comment by maleadt** [comment]
Then I'm not sure what you expected to happen.
