### ISSUE TITLE
0.4 compatibility

### ISSUE THREAD

**Issue by Cody-G** [JuliaGPU/CUDAdrv.jl#5]
Is there any plan to make this package compatible with 0.4?  Since CUDArt now relies on CUDAdrv, this package enforces a 0.5 requirement for CUDArt as well.  Thanks!

**Comment by maleadt** [comment]
The current [tagged version](https://github.com/JuliaGPU/CUDAdrv.jl/blob/c0cb8c0ea447ab4c9943e2a3653b0cebf8feb216/REQUIRE) is compatible with 0.4, so as long as CUDArt doesn't rely on features not in CUDAdrv v0.1.0 everything should be fine, right?

**Comment by Cody-G** [comment]
Oh my mistake!  I looked only at the README in the master branch.  Thanks!
