### ISSUE TITLE
Buffer Pooling

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CUDAdrv.jl#64]
On top of #60 we will want some kind of pooling for buffers similar to Knet's, to avoid CUDA's slow malloc.

This will probably take some tuning, but as a starting point I don't think this should be as fine grained as Knet's current approach, so that it works well when there's variety of array sizes. A good compromise might be to allocate real pointer in powers of two (similar to what base julia does now for `push!`). Then, looking up the right pool is trivial arithmetic, and you just have to handle cache misses in a reasonable way.

This feature should be optional; it's appropriate for end users, but devs may want more control, not least so that tools like cuda-memcheck work correctly.

**Comment by pevnak** [comment]
How this memory allocator would differ from buddy allocator (https://en.wikipedia.org/wiki/Buddy_memory_allocation)? It might be wise to stick with proven design, where drawbacks are known.

**Comment by MikeInnes** [comment]
I agree with the sentiment and, since I'm mostly making this up as I go along, I'm open to suggestions. But the buddy allocator is designed for managing space at the driver level rather than to give any kind of reuse. We can leave space management to CUDAdrv unless we have a really compelling reason not to.

**Comment by MikeInnes** [comment]
I had a quick go at this in https://github.com/JuliaGPU/CuArrays.jl/commit/a27b4faecc133523e6a1849c8f8cc32b8257c6b6. It'll certainly need some tuning on larger programs, but in the simplest cases it can make allocation about 1000x faster.
