### ISSUE TITLE
Precompilation cachefile not updated after failed build with --compilecache=no

### ISSUE THREAD

**Issue by dfdx** [JuliaGPU/CUDAdrv.jl#68]
After updating CUDAdrv and CUDAnative to their latest masters I'm getting the LoadError whenever I try to use CUDAnative:

```
julia> using CUDAdrv
WARNING: CUDAdrv.jl has not been configured, and will not work properly.
WARNING: Please run Pkg.build("CUDAdrv") and restart Julia.

julia> Pkg.build("CUDAdrv")
INFO: Building CUDAdrv
WARNING: Found multiple CUDA driver installations: /usr/lib/x86_64-linux-gnu and /usr
INFO: CUDAdrv.jl has already been built for this toolchain, no need to rebuild

julia> Pkg.build("CUDAnative")
INFO: Building LLVM
INFO: LLVM.jl has already been built for this toolchain, no need to rebuild
INFO: Building CUDAdrv
WARNING: Found multiple CUDA driver installations: /usr/lib/x86_64-linux-gnu and /usr
INFO: CUDAdrv.jl has already been built for this toolchain, no need to rebuild
INFO: Building CUDAnative
WARNING: CUDAdrv.jl has not been configured, and will not work properly.
WARNING: Please run Pkg.build("CUDAdrv") and restart Julia.
WARNING: Found multiple CUDA toolkit installations: /usr/local/cuda and /usr/local/cuda/targets/x86_64-linux
===============================================================================================[ ERROR: CUDAnative ]================================================================================================

LoadError: CUDAdrv.jl has not been configured.
while loading /home/dfdx/.julia/v0.6/CUDAnative/deps/build.jl, in expression starting on line 199

====================================================================================================================================================================================================================

==================================================================================================[ BUILD ERRORS ]==================================================================================================

WARNING: CUDAnative had build errors.

 - packages with build errors remain installed in /home/dfdx/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("CUDAnative")`
 - build a single package by running its `deps/build.jl` script
```
Previously everything worked fine. Are there any known version compatibility issues in recent versions?

**Comment by maleadt** [comment]
Gah, this `ext.jl` business is driving me nuts. I presume you've built the package with `--compilecache=no` or similar:

```
$ rm -f deps/ext.jl 
$ julia -e "using CUDAdrv" 
WARNING: CUDAdrv.jl has not been configured, and will not work properly.
WARNING: Please run Pkg.build("CUDAdrv") and restart Julia.

$ julia --compilecache=no -e 'Pkg.build("CUDAdrv")' 
INFO: Building CUDAdrv

$ julia -e "using CUDAdrv" 
WARNING: CUDAdrv.jl has not been configured, and will not work properly.
WARNING: Please run Pkg.build("CUDAdrv") and restart Julia.
```

With https://github.com/JuliaGPU/CUDAdrv.jl/commit/eddd27ac3b6a28fb1e78e94ab868082f9db80a99 I don't longer force recompilation when `--compilecache` is off, or you get nasty errors. But as a consequence, the cache can get "polluted" with a cachefile from when CUDAdrv wasn't configured (or failed to build) and hence `ext.jl` didn't exist. Just creating `ext.jl` doesn't trigger recompilation of the cachefile though. Let me try yet another approach.

I'm surprised I haven't seen anybody else run into this.

**Comment by maleadt** [comment]
Could you try #69?

**Comment by dfdx** [comment]
Now script fails on [this line](https://github.com/JuliaGPU/CUDAdrv.jl/pull/69/files#diff-224606f33d729e5278b5c695308380eaR12) because `include()` returns string (previously you checked file for existence instead).

**Comment by maleadt** [comment]
Oh right, with the old `ext.jl` format that'll fail indeed. I'll add a check.

**Comment by maleadt** [comment]
OK fixed, but it'll still fail when updating CUDAdrv and loading the package without building it. But it'll be fixed when running `Pkg.build`. This is compatible with most people's workflow (ie. using `Pkg` to update).

**Comment by dfdx** [comment]
Confirmed, works like a charm, thank you!

**Comment by maleadt** [comment]
Great! I'll tag CUDAdrv and see if any issues arise, if not I'll be applying the same fix to maleadt/LLVM.jl#67 JuliaGPU/CUDAnative.jl#136 JuliaGPU/CUDArt.jl#107
(ie. you might be running into this very issue for other packages in the meantime)
