### ISSUE TITLE
Unexciting issue running documentation portion of the tests

### ISSUE THREAD

**Issue by amellnik** [JuliaGPU/CUDAdrv.jl#79]
If I run the contents of `runtests.jl` (minus the documentation portion) in the REPL everything passes without issue.  However, if I run `Pkg.test("CUDAdrv")` or `cd(joinpath(Pkg.dir("CUDAdrv"), "test")); include("runtests.jl")` then the tests stall out right after I see `INFO: Testing using device...`.  without any error.  

I root-caused this to `include("documentation.jl")`.  Is this expecting a specific version of Documenter?  This may also be some windows-specific issue.

**Comment by maleadt** [comment]
>  Is this expecting a specific version of Documenter?

No, I'm just using the latest tagged version (as is CI). Could you post some version information (CUDA, packages, Julia)? I'll try and reproduce.

**Comment by maleadt** [comment]
Also, if you CTRL-C, where does the backtrace put you?

**Comment by amellnik** [comment]
The backtrace does not provide any information.  It's something in this block:

```julia
out = Pipe()
result = cd(joinpath(dirname(@__DIR__), "docs")) do
    withenv("TEST"=>true) do
        cmd = julia_cmd(`make.jl`)
        success(pipeline(cmd; stdout=out, stderr=out))
    end
end
close(out.in)
```

(where I typically replace `@__DIR__` with `Pkg.dir("CUDAdrv")` since I'm running this in the REPL or jupyter).  Looking at this more, it doesn't have anything to do with `Documenter` since I can 

```julia
cd(joinpath(Pkg.dir("CUDAdrv"), "docs"))
include("make.jl")
```
without issues.  The offending line is apparently `success(pipeline(cmd; stdout=out, stderr=out))` -- replacing that with just `run(cmd)` also works.

**Comment by amellnik** [comment]
This actually looks like a bug with `pipeline` and not this package at all -- removing the removing the stdout and stderr redirects prevents it from hanging:

```julia
result = cd(joinpath(Pkg.dir("CUDAdrv"), "docs")) do
    withenv("TEST"=>true) do
        cmd = julia_cmd(`make.jl`)
        #success(pipeline(cmd; stdout=out, stderr=out))
        success(pipeline(cmd))
    end
end
```

Edit: it looks like some interaction between `Documenter` and `pipeline`:

```julia
out = Pipe()
cmd = `julia -e "using Miniball"`
success(pipeline(cmd))  # Works
success(pipeline(cmd; stdout=out, stderr=out)) # Works

cmd = `julia -e "using Documenter"`
success(pipeline(cmd))  # Works
success(pipeline(cmd; stdout=out, stderr=out)) # Hangs
```

**Comment by maleadt** [comment]
Sorry, forgot about this. Thanks for looking into the issue, I'll just disable the (pretty hacky) doctest failure detection. This should arguably be a feature of Documenter.jl.
