### ISSUE TITLE
Cvoid not defined when importing package

### ISSUE THREAD

**Issue by jesusfv** [JuliaGPU/CUDAdrv.jl#80]
I am working on Ubuntu 17.10, CUDA 9.1, and Julia 0.6.2. My CUDA drivers work: I just run a C++ code with CUDA.

My process has been:

```Pkg.add("CUDAdrv")```

works fine, when I try again 

```
INFO: Package CUDAdrv is already installed
```

```Pkg. build("CUDAdrv")```

with the result:

```
INFO: Building CUDAdrv
WARNING: Found multiple CUDA driver installations: /usr/lib/x86_64-linux_gnu and /usr
```

Next, I type

```
using CUDAdrv
INFO: Precompiling module CUDAdrv
ERROR: LoadError: LoadError:

UndefVarError:Cvoid not defined
Stacktrace:
```
 ------bunch of additional stuff (I am not writing this in the same computer, so it is hard to copy the whole thing-------
```
failed to precompile CUDAdrv to <my directory here>
```

Same outcome if I skip `Pkg. build("CUDAdrv")` and invoke directly using CUDAdrv.

I saw this https://github.com/JuliaGPU/CUDAdrv.jl/issues/68 but it does not seem to be the same problem (even if the error message is the same with `Pkg. build("CUDAdrv")`).

Any suggestions?

I'd like to use the package for some very basic teaching of Julia with GPUs

**Comment by maleadt** [comment]
Thanks for the report. I can confirm this issue, will fix and tag ASAP.

To minor nits: please use block quotes for code snippets etc (using backticks), and posting the full stack trace is always relevant (because that allows me to see where the error happened, if it even is in CUDAdrv.jl's code, etc).

**Comment by maleadt** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/12881

**Comment by maleadt** [comment]
Fixed and tagged; `Pkg.update` should resolve this.

**Comment by jesusfv** [comment]
I use ```Pkg.update()``` and I get

```
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove
```

```using CUDAdrv``` produces same error as before.

If I use ```Pkg.update("CUDAdrv")```, I get

```
INFO: Updating METADATA...
INFO: Computing changes...
INFO: Package CUDAdrv was to set to version 0.7.4, but a higher version 0.7.6 exists. 
To install the latest version, you could try doing a full update with 'Pkg.update()'
INFO: No packages to install, update or remove
```

I tried the whole thing several times, no luck.
I also tried removing the package and installing it again, no luck (including closing and opening Julia between steps). It always installs version 0.74:

```Pkg.add("CUDAdrv")```

```
INFO: Installing CUDAapi v0.3.0
INFO: Installing CUDAdrv v0.7.4
INFO: Building CUDAdrv
WARNING: Found multiple CUDA driver installations: /usr/lib/x86_64-linux_gnu and /usr
INFO: Package database updated
```
Any idea why is reinstalling v0.7.4 instead of the new one? How to fix it?

Thanks!

**Comment by maleadt** [comment]
CUDAdrv is probably being held back through a dependency from another package, probably CUDAapi. eg. https://github.com/JuliaGPU/CUDNN.jl/issues/13
