### ISSUE TITLE
libcuda only found in toolkit

### ISSUE THREAD

**Issue by goretkin** [JuliaGPU/CUDAdrv.jl#89]
https://github.com/JuliaGPU/CUDAdrv.jl/blob/9ff699f65c1077fdb7039673eaf55d17f00b6160/deps/build.jl#L55 

was not working for me. I changed it to

`find_cuda_library("cuda", find_toolkit())`, and it worked.

**Comment by maleadt** [comment]
I removed that because `libcuda` is provided by your system (installed in system locations), and shouldn't be part of the CUDA toolkit.

Can you give some specifics? eg. how did you install the CUDA driver, where is libcuda located, etc.

**Comment by goretkin** [comment]
Ah, I understand.

I installed the CUDA toolkit from https://developer.nvidia.com/cuda-90-download-archive?target_os=MacOSX&target_arch=x86_64&target_version=1012 (the highest version that supports my version of macos) 

Mine appears to be installed at `/usr/local/cuda/lib/libcuda.dylib`

and
```
julia> CUDAapi.find_toolkit()
1-element Array{String,1}:
 "/usr/local/cuda"
```

I guess I don't see anywhere else that points to the system locations, but I might not be looking in the right place.
points to that.

**Comment by maleadt** [comment]
Ah, so I guess on macOS the CUDA driver library _is_ shipped as part of the toolkit. Will need to adjust the logic for that.

Out of curiosity, is the kernel module then also located (and loaded from) `/usr/local/cuda`?

**Comment by goretkin** [comment]
I'm not sure what to look for.  There are no cuda-related `*.kext` or `*.ko` filenames.
