### ISSUE TITLE
Zero-size allocation

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CUDAdrv.jl#92]
```julia
julia> Mem.alloc(0)
ERROR: ArgumentError: invalid amount of memory requested
```

I think it'd make sense if this worked (can just store a C_NULL pointer and 0 length). Otherwise you have to special-case this in a lot of higher-level code.

For example, if I have a growable "workspace" buffer stored in a global `Ref{CuVector{UInt8}}`, I currently have to initialise it with a one-byte CuVector, which is an unnecessary allocation.

**Comment by maleadt** [comment]
Can do. Originally designed this way because `cuMemAlloc` itself fails for 0-byte allocations, and CUDAdrv generally sticks to the CUDA API's behavior. But if you have legitimate use cases, we can consider this.
Will need to make sure this is robustly used in CUDAnative, because it also served as a failsafe against passing ghost arguments (which also have size 0).

**Comment by MikeInnes** [comment]
I think there's a basic language difference there, in that `alloc(0)` is basically always going to mean something is wrong in C, and where you need it you can just use `NULL`. Whereas in Julia (1) generics mean this comes up frequently as a special case, and (2) strong typing means you can't just use a sentinel, it has to be backed by the same buffer type.

Not sure if it's what you mean by ghost arguments, but it'd also make sense to support `CuVector{Nothing}` etc.

**Comment by maleadt** [comment]
> alloc(0) is basically always going to mean something is wrong in C

Not really, `malloc(0)` is actually supported by the spec, and error codes can be returned independently from the pointer.

But that doesn't really matter, I agree that this is a good design decision. I'll adapt the code soon.

> ghost arguments

Those are really just values that do not get an instance, eg. zero-size or singletons. CUDAnative needs to handle these separately, and the fact that they have size 0 proved a good failsafe to protect against these.

```
julia> struct Ghost end

julia> Core.sizeof(Ghost)
0

julia> foo(::Ghost) = nothing
foo (generic function with 1 method)

julia> @code_llvm foo(Ghost())

define void @julia_foo_62749() #0 !dbg !5 {
top:
  ret void
}
```
